### ISSUE TITLE
有关日历视图的疑惑

### ISSUE THREAD

**Issue by SoniaWang121** [quanru/obsidian-example-LifeOS#10]
您好，
    我是曾经在Zoom里试用过一次的用户，现在遇到2个疑惑：
1. 无法使用日历视图
我安装的插件和Calender plugin设置如图：
<img width="1053" alt="Screenshot 2023-07-12 at 20 43 33" src="https://github.com/quanru/obsidian-example-LifeOS/assets/57210111/f978e334-1c80-41a9-9f1f-fff522567730">
已自行谷歌，试了一些通用方法未解决。
请问是否还需要别的设置？

2. 类似于Apple Reminder的Today，是否有查询语句或解决方案能够查询【当日所有TASK】

感谢你的时间

**Comment by quanru** [comment]
1. 应该有一个按钮的：![image](https://github.com/quanru/obsidian-example-LifeOS/assets/11739753/0ed47859-83d0-4c0d-abbb-f90c03793874)
2. 或者建议你重新下载最新的，你只把你动过的文件覆盖到新的目录即可：https://github.com/quanru/obsidian-example-LifeOS/releases/latest/download/LifeOS.zip

**Comment by SoniaWang121** [comment]
感谢回复～
