### ISSUE TITLE
周期笔记的daily teamplate问题

### ISSUE THREAD

**Issue by ksaynice** [quanru/obsidian-example-LifeOS#18]
周期笔记的daily teamplate里面最后的记账是没有被正确显示的 包括示例里面daily/2023/6月下的都有这个问题

**Comment by quanru** [comment]
![image](https://github.com/quanru/obsidian-example-LifeOS/assets/11739753/74e63d1e-526c-4214-a47d-8fc7b1657c44)

周末才会有记账，这个是 Templater 的语法

**Comment by ksaynice** [comment]
明白 刚才又看了一遍 理解了

**Comment by ksaynice** [comment]
这个貌似跟时区有关系 如果在亚洲 Weekday + 1 <= 5 周五会不算weekday 周日会算 @quanru

**Comment by quanru** [comment]
时区和语言设置会影响每周是从周日还是周一开始算
