### ISSUE TITLE
与第三方插件thino的一处冲突

### ISSUE THREAD

**Issue by chinyajie** [quanru/obsidian-example-lifeos#23]
您好，非常感谢您提供的lifeos系统，目前我处在初步探索期待，但是已经收获了很多惊喜。
我在使用lifeos前使用了另一款obsidian插件thino对应地址https://github.com/Quorafind/Obsidian-Thino ，这款插件提供类似于flomo样式的每日子弹笔记的整合页面，同时具有灵活的快捷键可以让我全局唤出后快速键入一条子弹笔记，这个效果类似使用quickadd在day note中快速追加。
thino软件的功能和lifeos原则上是可以很好互补的，但是使用的时候我发现了一处小的bug，即在当天的day note文件尚未创建时，如果我使用thino创建一条子弹笔记（我怀疑使用quickadd可能也有类似问题），此时lifeos系统会创建当天的day note，但是最后并没有出现我插入的子弹笔记。后续我再使用thino写入子弹笔记，那么day note中会出现。
简而言之，问题就是如果day note笔记尚未通过lifeos系统创建时，我使用thino创建子弹笔记，那么lifeos会创建day note但是忽略掉这条子弹笔记本身。我使用未安装lifeos的空白库再使用thino创建子弹笔记时没出现这个问题，obsidian的日历插件会自动创建day note并记录子弹笔记。
感谢您耐心读完这条issue，谢谢～

**Comment by quanru** [comment]
lifeos 只会识别特定目录下的日记文件，并在文件的『日常记录』模块插入，你需要自己保证
