### ISSUE TITLE
模版路径问题

### ISSUE THREAD

**Issue by knightelvis** [quanru/obsidian-example-lifeos#24]
今天刚刚上手尝试lifeos，发现在创建periodic note的时候会出现找不到模版的问题。好像是路径不match：
plugin尝试去`PeriodicNotes/Templates/Daily.md`去找，但是官方的example里面给的路径是`0. PeriodicNotes`. 把这个文件夹重新命名为`PeriodicNotes`以后，就可以创建新的note了
<img width="1905" alt="Screenshot 2024-04-27 at 4 39 11 PM" src="https://github.com/quanru/obsidian-example-lifeos/assets/174577/dd23195a-c844-4989-9b35-9314af48deee">
<img width="302" alt="Screenshot 2024-04-27 at 4 39 22 PM" src="https://github.com/quanru/obsidian-example-lifeos/assets/174577/81ebc09c-7bc2-46a8-90b7-b3acbbd04652">

**Comment by quanru** [comment]
我看了下没问题的，你是不是把模版和插件分开下载了

**Comment by knightelvis** [comment]
呃.. 确实分开下载的。可以一起下载吗？(刚开始上手使用obsidian，所以不太熟悉)

**Comment by quanru** [comment]
分开就得自己设置对了，照着插件的配置文档

**Comment by knightelvis** [comment]
在plugging setting 里找到了配置，把 `PeriodicNotes` 改成 `0. PeriodicNotes` 后，问题解决了

<img width="810" alt="Screenshot 2024-04-27 at 5 04 14 PM" src="https://github.com/quanru/obsidian-example-lifeos/assets/174577/8c488ce0-c542-48ad-8dc9-c12d6eac64f9">
