### ISSUE TITLE
bug: 新功能 Chinese Calendar 打开后，修改日历窗口大小，功能会失效

### ISSUE THREAD

**Issue by kaimz** [quanru/obsidian-example-lifeos#26]
![image](https://github.com/quanru/obsidian-example-lifeos/assets/25757587/d67d1738-f231-48a1-8cd6-559f2890fda5)
我在拖动窗口大小后，农历和节假日将会消失（恢复未打开这个设置的模样）

**Comment by kaimz** [comment]
osx 14.5 
obsidian v1.6.5

**Comment by quanru** [comment]
更新到最新的插件版本呢？我这边未复现
